-- lua/config/keymaps.lua
local M = {}

local function map(mode, lhs, rhs, desc, extra)
	vim.keymap.set(mode, lhs, rhs, vim.tbl_extend("force", { silent = true, desc = desc }, extra or {}))
end

-- Register all global keymaps. Called from the which-key plugin config.
M.setup = function()
	-- Misc
	map({ "n", "x" }, "<leader>cp", '"+y', "Copy to system clipboard")
	map({ "n", "x" }, "<leader>cv", '"+p', "Paste from system clipboard")
	map("n", "<Esc>", "<cmd>nohlsearch<CR>", "Clear search highlight")
	map("n", "<leader>tn", "<cmd>set relativenumber!<cr>", "Toggle relative numbers")
	map("n", "<leader>uh", function()
		local bufnr = vim.api.nvim_get_current_buf()
		vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = bufnr }), { bufnr = bufnr })
	end, "Toggle Inlay Hints")

	-- Toggle
	map("n", "<leader>th", function()
		local bufnr = vim.api.nvim_get_current_buf()
		vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = bufnr }), { bufnr = bufnr })
	end, "Toggle Inlay Hints")
	map("n", "<leader>tf", function()
		require("functions.toggle-format").toggle()
	end, "Toggle Format on Save")
	map("n", "<leader>tT", "<cmd>Themery<cr>", "Change theme")
	map("n", "<leader>tt", "<cmd>TransparentToggle<cr>", "Toggle Transparency")
	map("n", "<leader>tw", "<cmd>Twilight<cr>", "Toggle Twilight")
	map("n", "<leader>ts", "<cmd>TabsVsSpacesToggle<cr>", "Tabs vs Spaces")
	map("n", "<leader>td", function()
		require("functions.toggle-diagnostics").cycle()
	end, "Cycle Diagnostics Display")

	-- NoNeckPain
	map("n", "<leader>nnp", "<cmd>NoNeckPain<cr>", "Toggle No Neck Pain")
	map("n", "<leader>nwu", "<cmd>NoNeckPainWidthUp<cr>", "Increase width")
	map("n", "<leader>nwd", "<cmd>NoNeckPainWidthDown<cr>", "Decrease width")
	map("n", "<leader>nns", "<cmd>NoNeckPainScratchPad<cr>", "Toggle scratchpad")

	-- Games
	map("n", "<leader>pbg", "<cmd>VimBeGood<cr>", "Vim Be Good")
	map("n", "<leader>pt", "<cmd>tetris<cr>", "Tetris")
	map("n", "<leader>ps", "<cmd>solitaire<cr>", "Solitaire")
	map("n", "<leader>pm", "<cmd>minesweeper<cr>", "Minesweeper")
	map("n", "<leader>pk", "<cmd>KillKillKill<cr>", "Killer Sheep")
	map("n", "<leader>pa", "<cmd>CellularAutomaton make_it_rain<cr>", "Make It Rain")
	map("n", "<leader>pA", "<cmd>CellularAutomaton game_of_life<cr>", "Game of Life")
	map("n", "<leader>pT", "<cmd>Typr<cr>", "Type test")

	-- Folds (UFO)
	map("n", "zR", function()
		require("ufo").openAllFolds()
	end, "Open all folds")
	map("n", "zM", function()
		require("ufo").closeAllFolds()
	end, "Close all folds")
	map("n", "zr", function()
		require("ufo").openFoldsExceptKinds()
	end, "Open folds except kind")
	map("n", "zm", function()
		require("ufo").closeFoldsWith()
	end, "Close folds with...")

	-- Hover
	map("n", "K", function()
		local ufo = require("ufo")
		if ufo and ufo.peekFoldedLinesUnderCursor and ufo.peekFoldedLinesUnderCursor() then
			return
		end
		require("pretty_hover").hover()
	end, "Peek fold or hover docs")
	map("n", "<C-n>", function()
		require("hover").hover_switch("next")
	end, "Next hover provider")
	map("n", "<C-p>", function()
		require("hover").hover_switch("previous")
	end, "Previous hover provider")

	-- Documentation
	map("n", "<leader>dd", "<cmd>DoxygenOpen<CR>", "Open Doxygen")
	map("n", "<leader>du", "<cmd>DoxygenUpdate<CR>", "Update Doxygen")

	-- Neogen
	map("n", "<leader>ng", function()
		require("neogen").generate()
	end, "Generate docs")
	map("n", "<leader>nf", function()
		require("neogen").generate({ type = "func" })
	end, "Function doc")
	map("n", "<leader>nc", function()
		require("neogen").generate({ type = "class" })
	end, "Class doc")

	-- Diagnostics / Trouble
	map("n", "<leader>xx", function()
		require("functions.toggle-trouble").toggle_below()
	end, "Diagnostics below code (Trouble)")
	map("n", "<leader>xX", function()
		require("functions.toggle-trouble").toggle_buffer_diagnostics()
	end, "Buffer Diagnostics (Trouble)")
	map("n", "<leader>cs", function()
		require("functions.toggle-trouble").toggle_symbols()
	end, "Symbols (Trouble)")
	map("n", "<leader>xr", function()
		require("functions.toggle-trouble").toggle_lsp()
	end, "LSP Definitions / References (Trouble)")
	map("n", "<leader>xL", function()
		require("functions.toggle-trouble").toggle_loclist()
	end, "Location List (Trouble)")
	map("n", "<leader>xQ", function()
		require("functions.toggle-trouble").toggle_qflist()
	end, "Quickfix List (Trouble)")
	map("n", "<leader>xi", function()
		require("functions.toggle-trouble").toggle_implement()
	end, "Implementations (Trouble)")
	map("n", "<leader>xtd", function()
		require("functions.toggle-trouble").toggle_typedef()
	end, "Type Definitions (Trouble)")

	-- File Tree (Neo-tree)
	map("n", "<Bar>", "<cmd>Neotree reveal<cr>", "Reveal file in Neo-tree")
	map("n", "rf", function()
		vim.cmd("Neotree float reveal_file=" .. vim.fn.expand("<cfile>") .. " reveal_force_cwd")
	end, "Reveal in float")
	map("n", "<leader>B", "<cmd>Neotree buffers toggle position=right<cr>", "Buffer list")
	map("n", "<leader>s", "<cmd>Neotree float git_status<cr>", "Git status (Neotree)")
	map("n", "<leader><space>", "<cmd>Neotree filesystem show<cr>", "Show filesystem")
	map("n", "<leader>o", "<cmd>Neotree toggle<cr>", "Toggle Neo-tree")
	map("n", "<leader>O", "<cmd>Neotree show<cr>", "Show Neo-tree")

	-- Bufferline
	map({ "n", "i" }, "<M-PageUp>", "<cmd>BufferLineCyclePrev<CR>", "Previous buffer")
	map({ "n", "i" }, "<M-PageDown>", "<cmd>BufferLineCycleNext<CR>", "Next buffer")
	map("n", "<leader>q", "<cmd>bp|bd #<CR>", "Close buffer")

	-- Smooth scrolling (neoscroll)
	map({ "n", "v", "x" }, "<C-k>", function()
		require("neoscroll").ctrl_u({ duration = 250 })
	end)
	map({ "n", "v", "x" }, "<C-j>", function()
		require("neoscroll").ctrl_d({ duration = 250 })
	end)
	map({ "n", "v", "x" }, "<C-b>", function()
		require("neoscroll").ctrl_b({ duration = 450 })
	end)
	map({ "n", "v", "x" }, "<C-f>", function()
		require("neoscroll").ctrl_f({ duration = 450 })
	end)
	map({ "n", "v", "x" }, "<C-y>", function()
		require("neoscroll").scroll(-0.1, { move_cursor = false, duration = 100 })
	end)
	map({ "n", "v", "x" }, "<C-e>", function()
		require("neoscroll").scroll(0.1, { move_cursor = false, duration = 100 })
	end)
	map("n", "zt", function()
		require("neoscroll").zt({ half_win_duration = 250 })
	end)
	map("n", "zz", function()
		require("neoscroll").zz({ half_win_duration = 250 })
	end)
	map("n", "zb", function()
		require("neoscroll").zb({ half_win_duration = 250 })
	end)
	map({ "n", "v", "x", "i" }, "<PageUp>", function()
		require("neoscroll").scroll(-vim.api.nvim_win_get_height(0) + 10, { duration = 250 })
	end, "Page Up")
	map({ "n", "v", "x", "i" }, "<PageDown>", function()
		require("neoscroll").scroll(vim.api.nvim_win_get_height(0) - 10, { duration = 250 })
	end, "Page Down")

	-- Telescope
	map("n", "<leader>ff", function()
		require("telescope.builtin").find_files()
	end, "Find Files")
	map("n", "<leader>fa", function()
		require("telescope.builtin").live_grep()
	end, "Live Grep")
	map("n", "<leader>fb", function()
		require("telescope.builtin").buffers()
	end, "Find Buffers")
	map("n", "<leader>fh", function()
		require("telescope.builtin").help_tags()
	end, "Help Tags")
	map("n", "<leader>fp", "<cmd>Telescope projects<CR>", "Find projects")
	map("n", "<leader>fgb", "<cmd>Telescope git_branches<CR>", "Git branches")
	map("n", "<leader>fgB", function()
		require("git_branch").files()
	end, "Git branch files")
	map("n", "<leader>fgc", "<cmd>Telescope git_commits<CR>", "Git commits")
	map("n", "<leader>fgs", "<cmd>Telescope git_stash<CR>", "Git stash")
	map("n", "<leader>fgS", "<cmd>Telescope git_status<CR>", "Git status")
	map("n", "<leader>fcb", function()
		require("telescope.builtin").git_bcommits()
	end, "Commits in buffer")
	map("n", "<C-l>", "<cmd>Telescope keymaps<CR>", "Keymap palette")

	-- Git
	map("n", "<leader>gp", function()
		vim.system({ "git", "pull" }, { text = true }, function(result)
			vim.notify(result.stdout)
		end)
	end, "Git Pull")
	map("n", "<leader>gb", "<cmd>Gitsigns toggle_current_line_blame<CR>", "Toggle git blame inline")
	map("n", "<leader>gB", "<cmd>Gitsigns blame_line<CR>", "Git blame for buffer")
	map("n", "<leader>ghp", "<cmd>Gitsigns preview_hunk_inline<CR>", "Preview hunk inline")
	map("n", "<leader>ghP", "<cmd>Gitsigns preview_hunk<CR>", "Preview hunk")
	map("n", "<leader>ghr", "<cmd>Gitsigns reset_hunk<CR>", "Reset hunk")
	map("n", "<leader>ghs", "<cmd>Gitsigns stage_hunk<CR>", "Stage hunk")
	map("n", "<leader>gid", "<cmd>Gitsigns toggle_word_diff<CR>", "Toggle inline diff")
	map("n", "<leader>gtn", "<cmd>Gitsigns toggle_numhl<CR>", "Toggle git num highlight")
	map("n", "<leader>gth", "<cmd>Gitsigns toggle_linehl<CR>", "Toggle git line highlights")
	map("n", "<leader>gts", "<cmd>Gitsigns toggle_signs<CR>", "Toggle git signs")
	map("n", "<leader>gl", "<cmd>Gitsigns setloclist<CR>", "Git to location list")
	map("n", "<leader>gf", "<cmd>Gitsigns setqflist<CR>", "Git to quickfix list")
end

M.lsp_mappings = function(bufnr)
	local o = { buffer = bufnr, silent = true }
	local function lmap(mode, lhs, rhs, desc)
		vim.keymap.set(mode, lhs, rhs, vim.tbl_extend("force", o, { desc = desc }))
	end

	lmap("n", "fr", "<cmd>Telescope lsp_references<CR>", "Find References")
	lmap("n", "gd", function()
		require("telescope.builtin").lsp_definitions()
	end, "Peek Definition")
	lmap("n", "gD", function()
		vim.lsp.buf.definition()
	end, "Go to Definition")
	lmap("n", "<leader>ca", function()
		require("tiny-code-action").code_action()
	end, "Code Action")
	lmap("n", "<leader>rn", function()
		vim.lsp.buf.rename()
	end, "Rename Symbol")
	lmap("n", "<leader>E", "<cmd>Trouble symbols toggle<CR>", "Toggle Outline")
	lmap("n", "gi", function()
		require("telescope.builtin").lsp_implementations()
	end, "Go to Implementation")
	lmap("n", "<leader>gR", function()
		require("telescope.builtin").lsp_references()
	end, "Find References")
	lmap("n", "<leader>sh", function()
		vim.lsp.buf.signature_help()
	end, "Signature Help")
	lmap("n", "[d", function()
		vim.diagnostic.jump({ count = -1, float = true })
	end, "Previous Diagnostic")
	lmap("n", "]d", function()
		vim.diagnostic.jump({ count = 1, float = true })
	end, "Next Diagnostic")
	lmap("n", "<leader>e", function()
		vim.diagnostic.open_float()
	end, "Show Diagnostic")
	lmap("n", "<leader>F", function()
		vim.lsp.buf.format({ async = true })
	end, "Format Code")
	lmap("n", "<leader>ws", function()
		vim.lsp.buf.workspace_symbol("")
	end, "Workspace Symbol")
end

M.dap_mappings = function(dap)
	map("n", "<F5>", dap.continue, "Start/Continue Debugging")
	map("n", "<F10>", dap.step_over, "Step Over")
	map("n", "<F11>", dap.step_into, "Step Into")
	map("n", "<F12>", dap.step_out, "Step Out")
	map("n", "<Leader>b", dap.toggle_breakpoint, "Toggle Breakpoint")
	map("n", "<Leader>cb", function()
		dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
	end, "Conditional Breakpoint")
	map("n", "<Leader>dr", dap.repl.open, "Open REPL")
	map("n", "<Leader>dl", dap.run_last, "Run Last Session")

	-- Harpoon
	map("n", "<leader>hp", function()
		require("harpoon"):list():add()
	end, "Harpoon file")
	map("n", "<leader>hq", function()
		require("harpoon").ui:toggle_quick_menu(require("harpoon"):list())
	end, "Harpoon menu")
	map("n", "<leader>hd", function()
		local hl = vim.fn.synIDattr(vim.fn.synID(vim.fn.line("."), vim.fn.col("."), 1), "name")
		print("Highlight group under cursor: " .. hl)
	end, "Show highlight group")
end

return M
